apiversion: v1
kind: service
metadata:
  name: mynamespace
  namespace: mynamespace
spec:
  type: NodePort
  selector:
    app: employeeservice
  ports:
    -port: 8080
    targetPort: 8080
    nodePort: 300081